//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P12T.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Article
    {
        public int ArticleId { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Content { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
    }
}
